### ISSUE TITLE
Something happened with versions I think

### ISSUE THREAD

**Issue by simonhutchings** [meilisearch/meilisearch-rails#114]
Was using connected to Dockerized version of Meilisearch using follwing config

```
MeiliSearch.configuration = {
  meilisearch_host: "http://#{Rails.application.credentials[:meilisearch][:host]}:#{Rails.application.credentials[:meilisearch][:port]}",
  meilisearch_api_key: Rails.application.credentials[:meilisearch][:key],
  pagination_backend: :kaminari,
  timeout: 2,
  max_retries: 1,
}
```

which translates to this

`{:meilisearch_host=>"http://localhost:7700", :meilisearch_api_key=>"thisIsAMasterKey", :pagination_backend=>:kaminari, :timeout=>2, :max_retries=>1}`

That was working and fine, and can still access the Mini dashboard with those credentials

But from yesterday afternoon, I started getting **NoMethodError (undefined method `qualified_version' for MeiliSearch:Module)** when running Order.reindex! or doing a search.

I updated to 0.4.1 and reimplemented the module in the Models with **include MeiliSearch::Rails** instead of **include MeiliSearch** and **MeiliSearch::Rails.configuration** in the configuration file, but now get **uninitialized constant MeiliSearch::Rails (NameError)** on start

Any ideas?

**Comment by brunoocasali** [comment]
Hey @simonhutchings thanks for reaching out!

I have a little trouble with the last release and it took me more time than I was expecting, but now should be fine.

I released a new version `v0.5.0` which is the last one, could you please update your gem and try again?
Maybe this issue that interest you #107 is related to what you're dealing with.

Let me know if this helps you in some way.

And thanks for using Meilisearch 🏅

**Comment by simonhutchings** [comment]
Great works in dev, but there isn’t a gem for that version yet, and every time I containerise it, it fails on run.

Any idea when you might push the gem version rather than having to compile from git?

Hutch

**Comment by brunoocasali** [comment]
Actually, I don’t know if totally followed your idea, but I already pushed the new version https://github.com/meilisearch/meilisearch-rails/releases/tag/v0.5.0

By the way, this v0.5.0 **only works** with Meilisearch server version **0.25.0** or greater :)

**Comment by grsahil20** [comment]
Here is my journey 

- Step 1 
```
gem install meilisearch-rails
Successfully installed meilisearch-rails-0.4.1
Parsing documentation for meilisearch-rails-0.4.1
Installing ri documentation for meilisearch-rails-0.4.1
Done installing documentation for meilisearch-rails after 1 seconds
1 gem installed
```
Result : Too old version

- Step 2
```
bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Could not find gem 'meilisearch-rails (= 0.5.1) x86_64-darwin-20' in any of the gem sources listed in your Gemfile.
```
Result : Fail


- Step 3
 ```
 gem "meilisearch-rails", github: "meilisearch/meilisearch-rails", branch: "release-v0.5.1"
```
  Success 👍

**Comment by brunoocasali** [comment]
@grsahil20 thanks for sharing! I understand what happened, the last version 0.5.0 never made it to the rubygems, my bad 😞 

After the breaking change, the file path changed accordingly, and I didn't check if the version was released or the release script.

Tomorrow the internal team will approve the PR #122 and I'll release it again :)
I let you and @simonhutchings informed.

**Comment by brunoocasali** [comment]
@grsahil20 and @simonhutchings can you try now? https://rubygems.org/gems/meilisearch-rails/versions/0.5.0

**Comment by simonhutchings** [comment]
0.5.0 just bundled from rubygems!

**Comment by brunoocasali** [comment]
Awesome @simonhutchings!

I'll close this since I assume the problem was the missing gem in the RubyGems. Feel free to reopen that if you think this is another mistake.

I'm sorry for the problematic release, hope this doesn't happen in the future.

Thanks, everyone for using Meilisearch ❤️
