### ISSUE TITLE
LoadError (cannot load such file -- meilisearch/ms_job)

### ISSUE THREAD

**Issue by jitingcn** [meilisearch/meilisearch-rails#124]
**Screenshots or Logs**
```
I, [2022-02-13T04:05:42.448366 #26]  INFO -- : [2b5c50a3-fcba-4272-b087-bab9f11de456] method=PATCH path=/entries/296 format=turbo_stream controller=EntriesController action=update status=500 error='LoadError: cannot load such file -- meilisearch/ms_job' duration=11.81 view=0.00 db=3.29
F, [2022-02-13T04:05:42.448883 #26] FATAL -- : [2b5c50a3-fcba-4272-b087-bab9f11de456]
[2b5c50a3-fcba-4272-b087-bab9f11de456] LoadError (cannot load such file -- meilisearch/ms_job):
[2b5c50a3-fcba-4272-b087-bab9f11de456]
[2b5c50a3-fcba-4272-b087-bab9f11de456] app/controllers/entries_controller.rb:73:in block in update'
[2b5c50a3-fcba-4272-b087-bab9f11de456] app/controllers/entries_controller.rb:62:in update
```

**Comment by jitingcn** [comment]
On my app, the meilisearch-rails jobs failed to load causing fail to update the meilisearch data when models were saved, and none of the other subsequent life cycle callback was being run, such as the `after_update_commit` needed for the `turbo stream` not running, causing the page to not be updated, which made my users notice the problem and report to me.

Another thing is this issue caused me to lose probably a few hours of audit logs (but this is mostly down to me not writing proper tests 🤡)

So I think this issue should be fixed and release a new version as soon as possible. @brunoocasali

**Comment by brunoocasali** [comment]
Shame on me, @jitingcn I made a lot of problems after this breaking-change :/

Most of the issues I had was because the code was not so good on coverage, but the idea is to improve this day-by-day. I'm sorry about this @jitingcn and thanks again for your time!

**Comment by brunoocasali** [comment]
Released https://rubygems.org/gems/meilisearch-rails/versions/0.5.1

**Comment by jitingcn** [comment]
Thanks. The next thing we can do is to add more tests for the jobs :)
