### ISSUE TITLE
Clarify pagy pagination usage in documents

### ISSUE THREAD

**Issue by jitingcn** [meilisearch/meilisearch-rails#126]
I noticed in the readme it mentions that the backend pagination backend now supports pagy.
But when I try this configuration it gave me an error.
```
MeiliSearch::Rails.configuration = {
  meilisearch_host: 'YourMeilisearchHost',
  meilisearch_api_key: 'YourMeilisearchAPIKey',
  pagination_backend: :pagy
}
```
After further investigation, the pagy backend pagination is provided by the pagy library and is different from other backend pagination setups. I think this needs to be clarified in the documentation.

**Comment by brunoocasali** [comment]
@jitingcn thanks for your issue!

Can you share the error with me? Btw, I don't have a lot of free time to dig into this, if you have any clue about how to solve this, we could work together 👯 

Thanks for contributing with Meilisearch 🤘

**Comment by jitingcn** [comment]
Error message is like:
```
Unknown pagination backend
/home/jiting/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/meilisearch-rails-93317e62d17a/lib/meilisearch/rails/pagination.rb:15:in `rescue in create'
/home/jiting/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/meilisearch-rails-93317e62d17a/lib/meilisearch/rails/pagination.rb:10:in `create'
/home/jiting/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/meilisearch-rails-93317e62d17a/lib/meilisearch-rails.rb:638:in `ms_search'
```

I haven't tried using pagy's meilisearch integration, but the documentation for it is here: https://ddnexus.github.io/pagy/extras/meilisearch

**Comment by jmarsh24** [comment]
The documents also reference adding ```ActiveRecord_Relation.include Pagy::Meilisearch``` to Model
