### ISSUE TITLE
Add each_with_hit and map_with_hits methods?

### ISSUE THREAD

**Issue by nimashariatian** [meilisearch/meilisearch-rails#130]
**Description**
Hi folks, thank you so much for this wonderful gem!
I think it would be pretty useful to add some handy collection methods to the result.

**Basic example**
Some examples for pseudocode :

```      
        def each_with_hits(&block)
          results.zip(raw_answer["hits"]).each(&block)
        end

        def map_with_hits(&block)
          results.zip(raw_answer["hits"]).map(&block)
        end
```

Would love to hear your thoughts!

**Comment by brunoocasali** [comment]
Hello, @nimashariatian thanks for your issue!

I would like to understand better your use cases to check if this could be a great addition to all the users!
We have some methods like `ms_raw_search` and `ms_raw_answer` that provide the entire answer, but we also have the `ms_search` and `search` which already answer with an array of AR objects.

Btw, I encourage you to make the changes with tests and submit a PR! I'll be happy to review!
We currently are working on the upgrade of all the SDKs to v0.26 so we do not have human resources to make this change :/

**Comment by brunoocasali** [comment]
I don't think we need these new methods since what we have is pretty simple:

```rb
hits = Book.search('harry pottre')
hits.each do |hit|
  puts hit.title
  puts hit.author
end
```

Please send a PR if you think that's a mistake on my side :)
