### ISSUE TITLE
Search within custom index (with pagy)

### ISSUE THREAD

**Issue by Svashta** [meilisearch/meilisearch-rails#131]
I am reading through the docs and it nicely describes how to create a custom index. So, now i have an index of all items and additional conditional index - in the same model.

I cannot not figure out how to limit my search (with or without pagy) to specific index.
Can some please explain how that is done, preferably with pagy.

Thx

**Comment by Svashta** [comment]
Ahh, to answer my own question and for anyone needing it;
Bot MeiliSearch .search and Pagy .pagy_search take index: parameter to define the scope.

**Comment by brunoocasali** [comment]
Hey, @Svashta I'm glad you could make it! 

If you want I invite you to contribute, with a PR adding better explanations about this in the docs?

**Comment by brunoocasali** [comment]
Closing, since it is not a real issue anymore :)
