### ISSUE TITLE
Search for a term on multiple models/Indexes

### ISSUE THREAD

**Issue by kofiasare** [meilisearch/meilisearch-rails#132]
**Description**
I have just migrated our application from searchkick to meilisearch however meilisearch doesn't have a way I can search for single term across multiple indexes or models like searchkick does.

**Basic example**
I want to to be able to search my term on at least one model

example:

``` ruby
Meilisearch.search(term, models: [...index_names])
```

**Comment by coder2000** [comment]
I have the same issue, there is an endpoint of the API where you can search a specific index, so you can add your data to a common shared index, but it isn't exposed by the library.

**Comment by kofiasare** [comment]
@coder2000 I don't want a commonly shared index. I want each model to have its own.

Anyways below is my workaround. Using parallel gem, I initiate parallel requests to the meilisearch endpoint
and await the result for both.

```ruby

# search_helper.rb

module SearchHelper
  SEARCH_MODELS = %w[AppUser Market Organisation]

  def search(args)
    raise Errors::SearchError::BlankQueryError if args[:query].blank?
    raise Errors::SearchError::UnpermittedQueryError if args[:query] == '*'

    models = args[:models].map { |m| m.tr(' ', '').camelize }
    if models.difference(SEARCH_MODELS).any?
      raise Errors::SearchError::UnknownSearchModelError
    end

    # your interest is here
    Parallel.flat_map(models, in_threads: models.size) do |m|
      m.constantize.search(args[:query])
    end
  end
end

```

**Comment by brunoocasali** [comment]
If I understood right @kofiasare what you want is not supported out of the box by Meilisearch (yet) 😢 
But this is planned to be done soon: https://roadmap.meilisearch.com/c/74-multi-index-search (you can vote if you want).

I saw your workaround, glad that worked for you!
Let me know if you need anything else. 

Thanks for using Meilisearch 🤘

**Comment by kofiasare** [comment]
@brunoocasali you are spot on. Closing issue then
