### ISSUE TITLE
Is it possible to deactivate Meilisearch on certain conditions?

### ISSUE THREAD

**Issue by BDav24** [meilisearch/meilisearch-rails#140]
**Description**
I'd like to be able to deactivate all requests to Meilisearch instance on a given condition.
For example to run tests, or to activate it on certain environments.

**Basic example**
I tried `meilisearch if: ->(_) { false }` but it sends a DELETE request.

And if I don't configure the service, I get `Please configure Meilisearch. Set MeiliSearch::Rails.configuration = {meilisearch_host: 'YOUR_MEILISEARCH_HOST', meilisearch_api_key: 'YOUR_API_KEY'} (MeiliSearch::Rails::NotConfigured)`.

It could be something like:
```
MeiliSearch::Rails.configuration = {
  activate: true | false (default: true)
}
```

**Comment by brunoocasali** [comment]
Hi @BDav24 thanks for your comment!

Do you mean, just enabling it but still having the ability to mock/stub the calls to `MeiliSearch::Rails` (without the real HTTP request), or literally enable/disable the service given a condition?

And do you see this configuration being used at the most during the app initialization or somewhere else in the code like `MeiliSearch::Rails.deactivate!`?

**Comment by BDav24** [comment]
Hi @brunoocasali 

> Do you mean, just enabling it but still having the ability to mock/stub the calls to MeiliSearch::Rails (without the real HTTP request), or literally enable/disable the service given a condition?

For my initial need I'd say both could work, so either one is fine.

> And do you see this configuration being used at the most during the app initialization or somewhere else in the code like `MeiliSearch::Rails.deactivate!`

`MeiliSearch::Rails.deactivate!` would work too, and would be more versatile (adding it to initial config should not be much if `deactivate!` is implemented anyway).

**Comment by brunoocasali** [comment]
Fantastic, I just wanted some options. Do you have any plans to submit a PR, it will be appreciated! 🥇 
We are entering a new release cycle, and the time will be short for me to work on this improvement.

**Comment by BDav24** [comment]
I didn't find an easy way to do that in the code.

It works on my side with:
```
class Book < ActiveRecord::Base
  include MeiliSearch::Rails if ...

  if ...
    meilisearch do
      attribute :title, :author
    end
  end
end
```

**Comment by brunoocasali** [comment]
Hi, @BDav24 sorry for the delay...

I had a hard time figuring out how to handle things when a meilisearch is inactive, but my best shot was implementing a NullObject pattern when the instance is inactive.

If you have time, can you try this https://github.com/meilisearch/meilisearch-rails/pull/177 locally?

The API is simple:

```rb
MeiliSearch::Rails.deactivate!
# or
MeiliSearch::Rails.deactivate! do
  # with meili disabled
end

MeiliSearch::Rails.active? # bool 

MeiliSearch::Rails.activate! # there is no block option here. Do you think it's necessary?
```

**Comment by brunoocasali** [comment]
And I forgot one, you can use:

```
MeiliSearch::Rails.configuration = {
   meilisearch_host: '...',
   meilisearch_api_key: '...',
   active: false|true
}
```

**Comment by BDav24** [comment]
Hi @brunoocasali, thanks for the heads up, I'll try that!

**Comment by brunoocasali** [comment]
Hi @BDav24, I'm waiting for review in that branch, and recently I pushed some changes, I realized that the code was error-prone to multi-threaded environments, but that should be fixed now.

If you ran that code in production or tested it locally, let me know if that was what you expected!

Thanks!
