### ISSUE TITLE
Per environment configuration as global option instead of per model

### ISSUE THREAD

**Issue by coder2000** [meilisearch/meilisearch-rails#142]
It would be nice if the `per_environment` configuration option could be set globally instead of on each model that uses meilisearch.

**Comment by brunoocasali** [comment]
Yeah! That's could be a really good improvement, totally agree with it!

If you have some time, go ahead and send us a PR! It will be appreciated! ❤️

**Comment by excid3** [comment]
Great idea @coder2000. 👍

**Comment by brunoocasali** [comment]
Hi, @coder2000. I made a PR #153 to implement. Feel free to test it locally and tell me if that solves your problem 😄
