### ISSUE TITLE
Add support to the typo tolerance customization

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-rails#146]
⚠️ This issue is generated, it means the examples and the namings do not necessarily correspond to the language of this repository.
Also, if you are a maintainer, feel free to add any clarification and instruction about this issue.

Related to:
- parent issue: https://github.com/meilisearch/integration-guides/issues/190
- specification: https://github.com/meilisearch/specifications/pull/117

----

⚠️ These https://github.com/meilisearch/meilisearch-ruby/issues/313, https://github.com/meilisearch/meilisearch-ruby/pull/311 should be finished before starting this issue!

Add a `typo_tolerance` index settings resource to manage customization of the typo tolerance feature at the index level.

```rb
class Book < ApplicationRecord
  include MeiliSearch::Rails

  meilisearch do
    # ...

    typo_tolerance enabled: true, 
      disable_on_attributes: [:title], 
      disable_on_words: ['york'],
      min_word_size_for_typos: { one_typo: 5, two_typos: 9 }
  end
end
```

More information about what the typo-tolerance field does could be [checked in the spec.](https://github.com/meilisearch/specifications/pull/117)

You could check the other customization methods for reference like: `synonyms`.

TODO:
- [ ] Add the `typo_tolerance` configuration
- [ ] Add tests

**Comment by doutatsu** [comment]
Any updates on this?

**Comment by brunoocasali** [comment]
Hi @doutatsu how are you?

Unfortunately, I don't have time to tackle this issue, but you can submit a PR if you want.

You can look at our [CONTRIBUTING guidelines](https://github.com/meilisearch/meilisearch-rails/blob/main/CONTRIBUTING.md) if you're interested in :)
