### ISSUE TITLE
Dynamic primary_key not working when searching?

### ISSUE THREAD

**Issue by mengqing** [meilisearch/meilisearch-rails#147]
**Description**
When using dynamic primary_key method, instead of using the value of that method, it tries to use the name of that primary_key

**Expected behavior**
```
class Cat < ActiveRecord::Base
  include MeiliSearch::Rails

  meilisearch index_uid: 'Animals', primary_key: :ms_id do
  end

  private
  def ms_id
    "cat_#{primary_key}" # ensure the cats & dogs primary_keys are not conflicting
  end
end
```
```
Cat.search('a cat')
# => Should return some data
```

**Current behavior**
```
Cat.search('a cat')
# => Caused by PG::UndefinedColumn: ERROR:  column cats.ms_id does not exist
```

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

**Environment (please complete the following information):**
- OS: OSX
- DB: Postgres 14.2
- Meilisearch server version: 0.26.1
- meilisearch-rails version: 0.5.1
- Rails version: 7.0.2.3

**Comment by brunoocasali** [comment]
Hi @mengqing! 

I was looking into the code and I found a similar use case in the specs: https://github.com/meilisearch/meilisearch-rails/blob/d44e2b9e1c78ba3d9c286494f4a4eb160adca8c6/spec/integration_spec.rb#L1325-L1334
and the setup:
https://github.com/meilisearch/meilisearch-rails/blob/d44e2b9e1c78ba3d9c286494f4a4eb160adca8c6/spec/integration_spec.rb#L211-L222

the setup used an `id: :ms_id` to specify the primary_key, can you try that, please?

**Comment by mengqing** [comment]
@brunoocasali I tried changing it to `id` and the issue is still happening.

That spec you highlighted used meilisearch ruby client to do the search, which I tried and it worked. But when I try to use the model class to do the search which it should return an array of records, failed

**Comment by brunoocasali** [comment]
Oh yes, you're correct, I missed the `.client.` part :/ 

I will give a look at a bunch of the rails/ruby gems issues this week or the next, feel free to open a PR if you need it ASAP.
Thanks for using Meilisearch and for reporting this bug to us! ❤️

**Comment by brunoocasali** [comment]
Hi @mengqing can you give more information about your use case, like:

- Where your `"cat_#{primary_key}"` comes from?
- Are you using STI?
- This `ms_id` method must be an instance method?

With this information, I can keep working in your issue, thanks! :)

**Comment by mengqing** [comment]
Hi @brunoocasali, I'm using the example in the README, https://github.com/meilisearch/meilisearch-rails#share-a-single-index, and it does not work.

```
class Cat < ActiveRecord::Base
  include MeiliSearch::Rails

  meilisearch index_uid: 'Animals', primary_key: :ms_id

  private

  def ms_id
    "cat_#{self.class.primary_key}" # ensure the cats & dogs primary_keys are not conflicting
  end
end
```

And I'm getting the following error

```
Caused by PG::UndefinedColumn: ERROR:  column cats.ms_id does not exist
```

**Comment by brunoocasali** [comment]
Hi @mengqing, from my perspective is fixed now, but can you try this branch https://github.com/meilisearch/meilisearch-rails/pull/176?
