### ISSUE TITLE
Unsure how to set API keys with Docker Compose

### ISSUE THREAD

**Issue by archonic** [meilisearch/meilisearch-rails#148]
I've got an instance booting and I can get default API keys but I'm wondering how a front-end key is supposed to be stored when restarting (`docker-compose down` then `docker-compose up`) regenerates the keys. This is what I've added to docker-compose.yml:

```
meilisearch:
  image: "getmeili/meilisearch:v0.26.1"
  env_file:
    - '.env'
  volumes:
    - "meilisearch:/data/data.ms"
  ports:
    - 7700:7700
```

I've been using Postman to get API keys after it boots then copying the "Default Search API Key" to my .env file. By the time I restart to pick up the env change, the keys are invalid. I tried creating a key in Postman but that gets nuked on restart as well. Am I missing some kind of persistence setting?

Update: I realized I hadn't set a volume. Now that I have a volume set, it isn't changing the behaviour.

**Comment by oluademola** [comment]
Hello @archonic 👋

Although I am not a docker expert but wouldn't it be a better idea to use the docker-compose stop option? Using the docker-compose down command stops containers and removes containers, networks, and volumes in other words this somehow resets the environment. It is the expected behavior that Meilisearch generates new values for the Default Search API Key and Default Admin API Key when the master key is changed as well as in the case of an environment reset.

Hope this helps. Many thanks 🙂

**Comment by archonic** [comment]
The typical way to exit after `docker-compose up` is `ctrl+c`. There's a well known bug however where `ctrl+c` doesn't actually kill the containers and ports are still in use. `docker-compose down` consistently closes the containers. It doesn't remove volumes. Even `docker system prune` doesn't remove volumes. You'd have to run `docker volume rm <volume id>` or `docker system prune -a` to destroy volumes.

It makes sense to roll the keys when the master key is changed, but I'm confused as to how people are working with MeiliSearch if it resets keys when the environment is reset. I've been running a stack with Redis and Elasticsearch, etc on docker-compose for years now. Redis is configured to use AOF and the volumes persist the environment from one restart to the next. If you restart your machine, is that also intended to reset keys for MeiliSearch? I must be missing something.

**Comment by archonic** [comment]
I think I understand what's happening here. I have one .env being provided to all my containers. Once MeiliSearch boots, I get the key and add it to the .env file so my Rails container has the front-end key. Then because the .env file changed, Meilisearch's environment has changed, so it rolls the keys again and the cycle restarts. I feel like Sisyphus.

I'll separate Meilisearch's env file and report back.

**Comment by oluademola** [comment]
Hi @archonic 

Does separating the env file resolve this issue?

**Comment by archonic** [comment]
Yes, it resolved it. Personally I wouldn't want the keys rolled when any environment variables change, even ones that aren't used by MeiliSearch, but I'll close the issue.

**Comment by archonic** [comment]
I'm actually still having problems with keys being regenerated even when the container's env file has no changes. I'll investigate more and reopen if I find out what's going on.

**Comment by archonic** [comment]
I've discovered that v0.27.0 will always roll the keys on every `docker-compose down/up` and v0.26.1 behaves as expected and doesn't roll the keys unless there's an environment change. This isn't the repository to discuss that but I figured I'd let anyone else know if they were trying to use docker compose.

**Comment by oluademola** [comment]
Hello @archonic 

I'm afraid I'm not able to reproduce this. I have tested with both versions with volume, and the keys remained the same after running `docker-compose down` and `docker-compose up`. They are not regenerated. In both versions, however, the keys were recreated without volume. It's also worth mentioning that with v0.27, your volume must be mounted in `/meili_ data `probably you are not doing this correctly. Here is my docker-compose file with volume:

```
version: "3.8"

volumes:
  meili:

services:
  meilisearch:
    image: getmeili/meilisearch:v0.27.0
    user: root
    ports:
      - "7700:7700"
    volumes:
      - "meili:/meili_data/"
    environment:
      - MEILI_MASTER_KEY=masterKey
      - MEILI_NO_ANALYTICS=true
```

Hope this helps

**Comment by oluademola** [comment]
Hi @archonic 

I am glad this resolved the problem for you. This behavior was introduced in v0.27, and it was mentioned in the breaking changes section of the release note. Perhaps this isn't obvious enough to users; we'd want to improve it, and we'd welcome your input. 

Thank you 🙏
