### ISSUE TITLE
Document difference between the use of `attribute` and `searchable_attributes`

### ISSUE THREAD

**Issue by JasonBarnabe** [meilisearch/meilisearch-rails#158]
The readme provides this example:

```ruby
class Book < ActiveRecord::Base
  include MeiliSearch::Rails

  meilisearch do
    attribute :title, :author # only the attributes 'title', and 'author' will be sent to Meilisearch
    # all attributes will be sent to Meilisearch if block is left empty
  end
end
```

Later, it provides this example:

```ruby
class Book < ApplicationRecord
  include MeiliSearch::Rails

  meilisearch do
    searchable_attributes [:title, :author, :publisher, :description]
    filterable_attributes [:genre]
    sortable_attributes [:title]
    ranking_rules [
      'proximity',
      'typo',
      'words',
      'attribute',
      'sort',
      'exactness',
      'publication_year:desc'
    ]
    synonyms nyc: ['new york']

    # The following parameters are applied when calling the search() method:
    attributes_to_highlight ['*']
    attributes_to_crop [:description]
    crop_length 10
  end
end
```

What is the difference between `attribute :title, :author` and `searchable_attributes [:title, :author, :publisher, :description]` (other than the additional attributes)? Are they equivalent? Does `attribute` additionally mark it as filterable/sortable?

Please document the answer.

**Comment by brunoocasali** [comment]
Hi @JasonBarnabe thanks for raising this issue!

Indeed the README is not that clear regarding the configuration, we will work on all of our READMEs soon with the help of the Docs team!

In the [final sentence here](https://github.com/meilisearch/meilisearch-rails#%EF%B8%8F-settings) we explain that all these settings are part of the [meilisearch configuration](https://docs.meilisearch.com/reference/features/settings.html).

So if you want you can set up all the index settings directly by using `curl` requests.

To answer your question, the `searchable_attributes` are a Meilisearch server configuration which implies: **fields in which to search for matching query words sorted by order of importance** if you don't specify anything Meilisearch will look over all the attributes when you make a search.

And the `attribute` is actually the data you choose to index :)

**Comment by brunoocasali** [comment]
CC: @guimachiavelli just mentioning you, to make you aware of some content we can improve in these READMEs :)

**Comment by JasonBarnabe** [comment]
@brunoocasali Thanks. So to be clear:

```ruby
  meilisearch do
    attribute :title, :author
  end
```
With above, only `title` and `author` are searchable.

```ruby
  meilisearch do
    searchable_attributes [:title, :author]
  end
```
With above, only `title` and `author` are searchable.

```ruby
  meilisearch do
    attribute :title, :author
    searchable_attributes [:title]
  end
```
With above, only `title` is searchable.

```ruby
  meilisearch do
  end
```
With above, `title`, `author`, and any other attribute of my model are searchable.

Correct?
