### ISSUE TITLE
Handling one-to-many in filterable attributes

### ISSUE THREAD

**Issue by JasonBarnabe** [meilisearch/meilisearch-rails#160]
Assume a `Book` has many `Author`s, and I want to be able to search for `Book` by `Author` name.

Can I do this?

```ruby
class Book
  meilisearch do
    attribute :authors do
      authors.map(&:name)
    end
  end
end
```

Or is there a better way to do it? (Please document)

**Comment by brunoocasali** [comment]
Yes you can do this @JasonBarnabe 😃 

You may have to deal with N+1 when reindexing. If I remember correctly you'll need to run something like `Book.includes(:authors).reindex!` to prevent it.
