### ISSUE TITLE
Eager loading associations

### ISSUE THREAD

**Issue by rolandasb** [meilisearch/meilisearch-rails#165]
👋

It would be great if MeiliSearch would support eager loading associations to avoid N+1 queries when reindexing. For example, here's my usecase:

```ruby
class User < ApplicationRecord
  has_many :memberships
  include MeiliSearch::Rails

  meilisearch do
    attribute :account_id do
      memberships.map(&:account_id)
    end
    filterable_attributes [:account_id]
  end
end
```

Simple scope overriding could work, for example:

```ruby
class User < ApplicationRecord
  scope :meilisearch_import -> { includes(:memberships) }
end
```

Let me know if it's ok and I'll open a PR. Thanks!

**Comment by brunoocasali** [comment]
Hi @rolandasb did you tried something like this:

```ruby
User.includes(:memberships).reindex!
```

**Comment by rolandasb** [comment]
That definitely works, but it could become tedious to explicitly define associations in every `reindex!` call, especially when one model needs to use multiple associated attributes. Also, one could argue it's a part of meilisearch configuration, thus it should live inside a model.

**Comment by brunoocasali** [comment]
I agree with this statement __"Also, one could argue it's a part of meilisearch configuration, thus it should live inside a model."__ but doing that we also have full control of the association loading.

But in any case, I think we definitely can add a scope as you suggested! But @rolandasb I currently do not have free time to work in this request, what do you think to contribute 😍 ?
