### ISSUE TITLE
Create index in model - without adding new documents right away

### ISSUE THREAD

**Issue by alcanari** [meilisearch/meilisearch-rails#178]
Hi, 

Hope you're doing well! 

On the rails doc, it says that to create my index, I should define it in the model:

> Add documents
> 
> The following code will create a Book index and add search capabilities to your Book model.
> 
> ```
> class Book < ActiveRecord::Base
>   include MeiliSearch::Rails
> 
>   meilisearch do
>     attribute :title, :author # only the attributes 'title', and 'author' will be sent to Meilisearch
>     # all attributes will be sent to Meilisearch if block is left empty
>   end
> end
> ```

So after each new creation, the document is also added to Meilisearch. But looking at the Indexation and performance documentation, I understand that this is not an ideal solution?

> Bigger HTTP payloads are processed more quickly than smaller payloads. For example, adding the same 100,000 documents in two batches of 50,000 documents will be quicker than adding them in four batches of 25,000 documents. By default, Meilisearch sets the maximum payload size to 100MB, but [you can change this value if necessary](https://docs.meilisearch.com/learn/configuration/instance_options.html#payload-limit-size). That said, the bigger the payload is, the higher the memory consumption will be. An instance may crash if it requires more RAM than is currently available in a machine.

I'm having important issues of performance on my application regarding indexing - I can receive daily 5k+ new documents.

Reading this, I understand that it would be better to batch them and send them as documents to Meilisearch on a daily basis, rather than one after the other all day long. I'm wondering if my issues are coming from this.

Is this possible? How can I avoid creating a new document each time?

Thank you, take care 🙏 

_PS - Running MeiliSearch 0.27.1 on Debian 10 on a Digital Ocean droplet (16 GB Memory / 160 GB Disk / AMS3 8vCPUs)_

**Comment by oluademola** [comment]
Hi @alcanari 

By default, the document addition request is processed one by one. You could enable the auto-batching feature to speed up the indexing process and mitigate the performance problem. When this feature is enabled, if documents are still sent one by one, the auto-batching feature will batch them automatically before indexing them. This configuration is only done at the instance level, and there is no specific rails config you'd need to do. You can enable this feature in your droplet by modifying the service file as follows: 
- ssh into the DO droplet
- run `systemctl stop meilisearch`
- run `nano /etc/systemd/system/meilisearch.service` and modify this file by adding the `--enable-auto-batching` flag
- then run ` systemctl restart meilisearch`

Hope this helps.

**Comment by brunoocasali** [comment]
I'm closing this, due to lack of activity. Feel free to reopen.
