### ISSUE TITLE
Multiple hits of the same primary key

### ISSUE THREAD

**Issue by mech** [meilisearch/meilisearch-rails#188]
I am using default ActiveRecord `id` as primary key (which I did not do any additional configuration) and I supposed MeiliSearch will use `id` to act as the key also. But somehow my result will show multiple hits of the same `id`.

<img width="732" alt="ol2sy_16_18_59" src="https://user-images.githubusercontent.com/5850/189518290-a0bab3ee-8066-479f-8a43-a2aacaaaeee3.png">

I am wondering if this is even possible? I know there is concept like "Distinct Attribute", but I thought primary key should be fixed?

**Environment:**
- OS: AWS 20.04.1-Ubuntu
- Meilisearch server version: v0.29.0-pagination.beta.3
- meilisearch-rails version: v0.7.2
- Rails version: v7.0.3.1

**Comment by oluademola** [comment]
Hello @mech. Meilisearch should indeed automatically look for an attribute containing the string `id `in your document field and set it as the index's primary key. The value of the id should be unique, and your case is a bit strange. Could you show me what meilisearch returns in JSON? Could you also set the primary key [explicitly](https://github.com/meilisearch/meilisearch-rails#custom-primary-key) and try again?

**Comment by mech** [comment]
Unfortunately I clear my data and have since unable to replicate this issues. I believe it is down to my seed re-executing repeatedly.
