### ISSUE TITLE
Disable typo tolerance on attributes - disableOnAttributes

### ISSUE THREAD

**Issue by jeremylynch** [meilisearch/meilisearch-rails#189]
Previously we were using `disableTypoToleranceOnAttributes` in Algolia. I am aware that typo tolerance can be disabled as per the [docs](https://docs.meilisearch.com/learn/configuration/typo_tolerance.html#configuring-typo-tolerance), however this is not covered in this library. 

How can we use `disableOnAttributes` in meilisearch-rails?

**Comment by oluademola** [comment]
Hello @jeremylynch 

What version of the rails package are you using? There is a great chance you might be using an older package that doesn't this feature.

**Comment by jeremylynch** [comment]
We are using 0.7.2, the latest available version as of 17th September

**Comment by oluademola** [comment]
Hello @jeremylynch,

Sorry for the inconvenience. You are right and there is an existing issue about the topic [here](https://github.com/meilisearch/meilisearch-rails/issues/146). We hope to add support for the typo tolerance settings very soon. 

Hope this helps. Thank you very much.

**Comment by brunoocasali** [comment]
I think I can close this issue since this is planned in the https://github.com/meilisearch/meilisearch-rails/issues/146 :)
