### ISSUE TITLE
Can't get Pagy to work -- MeiliSearch::Rails::BadConfiguration (Unknown pagination backend)

### ISSUE THREAD

**Issue by k2director** [meilisearch/meilisearch-rails#201]
**Description**
First time trying to get Meilisearch working with my app, which uses Pagy, but while Meilisearch is working from the Rails console, I can't get any page that uses Pagy to actually load without the BadConfiguration error. 

**Expected behavior**
An index page using Pagy should load and display properly! ;-)

**Current behavior**
Crash with "Unknown pagination backend" error....

[NoMethodError: undefined method `create' for Pagy:Class ::MeiliSearch::Rails::Pagination.const_get(backend).create(results, total_hits, options) ^^^^^^^](http://localhost:3000/sources?term=squid&commit=Search#)

I've double-checked all the necessary steps that are required to get Pagy working, including: 
1)  In my meilisearch.rb initializer file.... 

`pagination_backend: :pagy`

2) In my "Source" model file, I have: 

`extend Pagy::Meilisearch `
`ActiveRecord_Relation.include Pagy::Meilisearch `
 

3) In my Sources index controller:

def index
    search = "squid"
    sources = Source.pagy_search(search)
    @pagy, @sources = pagy_meilisearch(sources, items: 10)
  end
 
4) Made sure my Pagy.rb initializer file includes the meilisearch extras...
`require 'pagy/extras/meilisearch`

5) Made sure I have the latest Pagy version (5.10.1) and read through the Pagy docs section on Meilisearch:
https://ddnexus.github.io/pagy/extras/meilisearch?ref=morioh.com&utm_source=morioh.com#gsc.tab=0

Hope this is helpful, I'm really excited to use Meilisearch in my app! Let me know if I can give you anything else...

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.
<img width="997" alt="Screen Shot 2022-10-15 at 5 37 00 PM" src="https://user-images.githubusercontent.com/58047065/196012510-f5a0840c-c070-4626-8ddd-b3602e364409.png">
e following information):**

**Environment**

- OS: Mac
- Meilisearch server version: latest...just installed today
- meilisearch-rails version: 0.7.3
- Rails version: 7.0.2.3

**Comment by brunoocasali** [comment]
Hi @k2director, thanks for raising this issue! We have other open issues regarding pagy documentation in this repository.

I think you don't need the `pagination_backend: :pagy` extra at all like mentioned here:  https://github.com/meilisearch/meilisearch-rails/issues/126#issuecomment-1067644814

Can you try that?

**Comment by k2director** [comment]
Bruno, thanks much for the quick reply. And for the solution: you were right, I just needed to omit that line, and it all started working. 
I'm happy to volunteer to put this in the documentation, if you guys are just waiting for someone to volunteer to update that. Otherwise, I'll close the issue.

**Comment by brunoocasali** [comment]
Hi @k2director, good to know it turns out right for you!

I'll be so happy if you could do that, you will also receive a gift from Meilisearch :D

We have two open issues about this subject. Take a look at those:
https://github.com/meilisearch/meilisearch-rails/issues/131
https://github.com/meilisearch/meilisearch-rails/issues/126

Any doubt, I'll be here to help you along the way!

I'll close this issue for now!

**Comment by k2director** [comment]
I will take a look and figure out my approach, thanks much!
