### ISSUE TITLE
Can't do AND search in Rails

### ISSUE THREAD

**Issue by sandonemaki** [meilisearch/meilisearch-rails#213]
For example, if I want to search for Alice and Bob in the first_name column, if I do `User.search("Alice", "Bob")`, it searches only for `Alice` and not for `Bob`.
 How can I use Rails to do an and search and or search in the same record, or an and search and or search with another record?

Currently, the only way to do this is to make an array of the searched terms, receive the values as params on the controller side, create an array for each space, then create an array of the searched records in the map and pass it to the view?
If so, will the highlighting process live?
```ruby
# controller
hits = params[:value]
@hits = 
hits.split(" ").map do |hit|
  User.search(hit)
end

# view
<% @hits.each do |hit| %>
  <%= hit.first_name %>
  <%= hit.family_name %>
<% end %>
```

**Comment by oluademola** [comment]
Hello @sandonemaki 

Sorry for the very late response. I am afraid this isn't possible with the search method. However, you could achieve this with a filter by filtering on the first_name column. For example, `filter: 'first_name = Bob AND first_name = Alice'` or `filter: 'first_name = Bob OR first_name = Alice'` would return documents containing these first names depending on the chosen criteria. You can find more information about filters in this [guide](https://docs.meilisearch.com/learn/advanced/filtering_and_faceted_search.html#filtering-and-faceted-search).

I hope this helps.

**Comment by brunoocasali** [comment]
I hope the @oluademola response has helped you @sandonemaki. Reopen this issue if you still need help!
