### ISSUE TITLE
Set maxValuesForFacet from the model settings

### ISSUE THREAD

**Issue by 0xMostafa** [meilisearch/meilisearch-rails#232]
**Description**
From the API, you can set `maxValuesPerFacet`, it's 100 by default. I want to set it from the settings on the model, same as `searchable_attributes` & `pagination`

i looked into the source code [here](https://github.com/meilisearch/meilisearch-rails/blob/62e1bfaf4deb4a5ab79ea593f7113c6f9eae6c78/lib/meilisearch-rails.rb#L50) and found that it's not implemented.

if it's not implemented, i can implement it.

to confirm, is it implemented?

**Comment by brunoocasali** [comment]
Hi @0xMostafa that's correct. It is not implemented yet. Feel free to send a PR 🥇
