### ISSUE TITLE
Add support for matching_strategy

### ISSUE THREAD

**Issue by doutatsu** [meilisearch/meilisearch-rails#240]
**Description**
This is a very important configuration option, that I require to switch to Meilisearch. I would have used the inline option, but unfortunately, I don't seem to be able to provide this option in combination with pagy search. 

**Basic example**
Trying to setup in the configuration:

```rb
 meilisearch enqueue: :reindex_search do
    searchable_attributes %i[title alt_titles]
    filterable_attributes %i[content_rating content_type]
    sortable_attributes %i[created_at available_chapters_count users_count]
    attributes_to_highlight %i[title alt_titles]
    matching_strategy 'all'
    pagination max_total_hits: 50_000
  end
```

Results in:
```rb
NoMethodError (undefined method `matching_strategy' for #<MeiliSearch::Rails::IndexSettings:0x0000000106ecaa20 @options={:enqueue=>:reindex_search}, @searchableAttributes=[:title, :alt_titles], @filterableAttributes=[:content_rating, :content_type], @sortableAttributes=[:created_at, :available_chapters_count, :users_count], @attributesToHighlight=[:title, :alt_titles]>):
```

I can inline this option, when using regular search:

<img width="621" alt="image" src="https://user-images.githubusercontent.com/4270980/219879049-76de9a2a-ec37-4616-bf2a-f8c989c846d6.png">

But not with `pagy_search`: 

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/4270980/219879072-3e24fab0-3076-45e3-8361-9d98a49f4313.png">

**Other**
Any other things you want to add.

**Comment by brunoocasali** [comment]
Hi @doutatsu 

The `matching_strategy` option is a search-time option, which means you can only use it during your search request! Check it out more here: https://docs.meilisearch.com/reference/api/search.html#matching-strategy

So it does not make sense to add it to your model. Still, you should be able to use it with pagy with this:

```rb
results = Task.pagy_search(params[:q], { matching_strategy: 'all' })
@pagy, results = pagy_meilisearch(results, items: 20)

render json: { hits: results, pagy: @pagy }
```

I can confirm it works with the latest `meilisearch-rails` and the latest `pagy` version. Can you confirm your meilisearch-rails/meilisearch engine and pagy versions?

**Comment by doutatsu** [comment]
Hi @brunoocasali - meilisearch-rails is version `0.8.1`, meilisearch is version `1.0.1`, and pagy is version `5.10.1`

**Comment by brunoocasali** [comment]
Can you update your pagy to v6? Some changes were implemented in the meilisearch extra in the pagy side for this new major version. If it does not work, I'll need more information to help you.

**Comment by doutatsu** [comment]
@brunoocasali I've updated to version 6 and I am still getting this error, unfortunately. I am on ruby `3.0.4` and rails `6.2` if that helps

**Comment by doutatsu** [comment]
More weirdness on my side - `pagy_search` doesn't return anything anymore, while regular ms_search does:

```rb
irb(main):008:0> MangaSeries.pagy_search('magic')
=>
[MangaSeries(id: integer, title: string, created_at: datetime, updated_at: datetime, kitsu_id: integer, mal_id: integer, title_en: string, title_en_jp: string, cover_data: jsonb, alt_titles: string, slug: string, content_rating: integer, available_chapters_count: integer, users_count: integer, content_type: integer, genres: string),
 "magic",
 {}]

irb(main):009:0> MangaSeries.ms_search('magic')
  MangaSeries Load (2.4ms)  SELECT "manga_series".* FROM "manga_series" WHERE "manga_series"."id" IN ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20)  [["id", 3566], ["id", 3986], ["id", 18521], ["id", 20933], ["id", 21298], ["id", 23980], ["id", 24322], ["id", 25850], ["id", 29140], ["id", 35497], ["id", 35498], ["id", 36733], ["id", 38366], ["id", 43481], ["id", 45715], ["id", 46066], ["id", 47150], ["id", 49113], ["id", 53402], ["id", 2769]]
=>
[#<MangaSeries:0x0000000110037d78
  id: 3566,
  title: "Magic Marriage",
```

I've also tried using passive mode as described [here](https://ddnexus.github.io/pagy/docs/extras/meilisearch/), which results in a different error... that supposed to have been fixed based on my investigation:

```rb
irb(main):010:0> series = MangaSeries.ms_search('magic')
  MangaSeries Load (1.4ms)  SELECT "manga_series".* FROM "manga_series" WHERE "manga_series"."id" IN ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20)  [["id", 3566], ["id", 3986], ["id", 18521], ["id", 20933], ["id", 21298], ["id", 23980], ["id", 24322], ["id", 25850], ["id", 29140], ["id", 35497], ["id", 35498], ["id", 36733], ["id", 38366], ["id", 43481], ["id", 45715], ["id", 46066], ["id", 47150], ["id", 49113], ["id", 53402], ["id", 2769]]
=>
[#<MangaSeries:0x00000001464f4df8
...
irb(main):011:0> Pagy.new_from_meilisearch(series)
/Users/doutatsu/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/pagy-6.0.2/lib/pagy.rb:96:in `block in setup_vars': expected :count >= 0; got nil (Pagy::VariableError)
```

**Comment by brunoocasali** [comment]
Just checking, are you adopting the `pagy` now? Or it used to work in older versions for example?
I would like to know if you followed all the steps required to setup pagy in the rails app + meili:

```rb
# create a new initializer at config/initializers/pagy.rb

require 'pagy/extras/meilisearch'
```

Then in your model, you must extend `Pagy::Meilisearch`:

```rb
class Book < ApplicationRecord
  include MeiliSearch::Rails
  extend Pagy::Meilisearch

  meilisearch # ...
end
```

Unfortunately, I can't figure out what's happening because I have a local setup here and everything seems to be fine :/ 

Maybe if you could reproduce the issue in a public rails-app it would be very very helpful to me.

**Comment by doutatsu** [comment]
So, I've figured it out, although I am puzzled why this works... When I omit hash and pass variables as is, everything works:
```rb
  MangaSeries.pagy_search(params[:search_term], matching_strategy: 'all')
```

instead of
```rb
  MangaSeries.pagy_search(params[:search_term], { matching_strategy: 'all' })
```

I am not sure why it works for you, but this change did the trick - and trying the hash still results in error for me 🤷🏻 Even though pagy extra clearly uses double splat operator...

```rb
    module Meilisearch # :nodoc:
      # Return an array used to delay the call of #search
      # after the pagination variables are merged to the options
      def pagy_meilisearch(term = nil, **vars)
        [self, term, vars]
      end
      alias_method DEFAULT[:meilisearch_pagy_search], :pagy_meilisearch
    end
```

So I'll close this issue now, thanks for pointing me in the right direction!
