### ISSUE TITLE
Multi Search Possible?

### ISSUE THREAD

**Issue by antarr** [meilisearch/meilisearch-rails#248]
I'm currently looking into migrating for elasticsearch/searchkick. I haven't seen any documentation on [Multi Search](https://github.com/ankane/searchkick#multi-search) support, i.e, searching multiple models with a single query. Is this supported?

**Comment by brunoocasali** [comment]
Hi @antarr!

If I understood your question correctly, you are considering changing from Elasticsearch to Meilisearch, and you want to use the multi-search feature searchkick has.
FYI, we are introducing this feature [in the following release of Meilisearch (v1.1)](https://github.com/meilisearch/product/discussions/615#discussioncomment-5238272), and its support on Meilisearch Rails will come soon (but I can't give you an estimation yet).

**Comment by brunoocasali** [comment]
Hi @antarr I'm going to close this issue, since the automation already opened an issue to track the subject around `multi_search`
