### ISSUE TITLE
problem support custom primary key

### ISSUE THREAD

**Issue by masukomi** [meilisearch/meilisearch-rails#251]
**Description**
this builds on #250 BUT if we fix that issue ... we run into the next one

[this line](https://github.com/meilisearch/meilisearch-rails/blob/b81d693f7f86497b804bb9c506c1661df65c89fb/lib/meilisearch-rails.rb#L648)

```
        condition_key = meilisearch_options[:type].primary_key if has_virtual_column_as_pk
```
calls the `primary_key` method on the model. Mongoid doesn't have a `primary_key` method and it seem to be doing anything with the fact that I've added the following to my model. It _should_ be calling my `ms_id` method but it's hardcoded to call `primary_key` 

```
meilisearch primary_key: :ms_id
```

this may actually be an issue that extends beyond mongoid, but i can't test that at the moment.

**Expected behavior**
call the primary key method i told it to.

**Current behavior**
it called `.primary_key` which is a non-existent method.

```
Task.find('foo')
/Users/masukomi/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/meilisearch-rails-0.9.0/lib/meilisearch-rails.rb:650:in `ms_search': undefined method `primary_key' for Task:Class (NoMethodError)

        condition_key = meilisearch_options[:type].primary_key if has_virtual_column_as_pk

```

**Environment (please complete the following information):**
- OS: [macOS]
- Meilisearch server version: [e.g. v.1.1.1] (irrelevant though)
- meilisearch-rails version: [e.g v0.9.0] 
- Rails version: [e.g. 7.0.4.3]

**Comment by masukomi** [comment]
the problem appears to be putting the `meilisearch primary_key: :ms_id` line after my `meilisearch do` block. If i move it above it it isn't a problem. The documentation does not show how to combine the block form and the non-block form and it's not clear how to specify a primary key in the block form (or if that's even possible) 

so, the temp fix here _may_ be to just fix the readme to provide examples of the block and non-block forms in the same model, OR documenting how to not need that. This would be until the longer term fix can be put in place such that ordering isn't important.

**Comment by brunoocasali** [comment]
Following my comment in the previous issue #250 we need to proper test and fix the issues in the MongoId.

**Comment by brunoocasali** [comment]
I'm going to close this issue because all the MongoDB requests are going to be tracked in the issue https://github.com/meilisearch/meilisearch-rails/issues/175.
