### ISSUE TITLE
Perform multiple searches in one single HTTP request

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-rails#254]
⚠️ This issue is generated, it means the examples and the namings do not necessarily correspond to the language of this repository.
Also, if you are a maintainer, feel free to add any clarification and instruction about this issue.

Sorry if this is already partially/completely implemented, feel free to let me know about the state of this issue in the repo.

Related to https://github.com/meilisearch/integration-guides/issues/251

----

Related to:
- issue: https://github.com/meilisearch/meilisearch/issues/3427
- spec: https://github.com/meilisearch/specifications/pull/225

Create a new **client method** called `multiSearch`/`multi_search`, which will request `POST /multi-search` with a body payload containing a structure similar to this:

```json
{
   "queries": [ 
      { "indexUid": "movie", "q": "wonder", "limit": 10 }, 
      { "indexUid": "books", "q": "king", "page": 2 } 
    ]
}
```
Each object is a simple search object sent in the `POST /indexes/:indexUid/search` request.

Pay attention to the response, which will follow the order of the requests object and will look like this (note the new `indexUid` key in the response):

```json
{
   "results": [ 
      {
         "indexUid": "movie",
         "hits": [ { "title": "wonderwoman" } ],
         // other search results fields: processingTimeMs, limit, ...
      },
      {
         "indexUid": "books",
         "hits": [ { "title": "king kong theory" } ],
         // other search results fields: processingTimeMs, limit, ...
      },
   ]
}
```

TODO:
- [ ] Add the new `multi_search` method
- [ ] Add tests

**Comment by ellnix** [comment]
Should this not first be added to [meilisearch-ruby](https://github.com/meilisearch/meilisearch-ruby)? I checked, but there was no issue for it, past or present.

**Comment by brunoocasali** [comment]
The `multi_search` works on ruby already :)

https://github.com/meilisearch/meilisearch-ruby/issues/489#issuecomment-1750645773

**Comment by jonathanfikunayomi** [comment]
No problem

**Comment by curquiza** [comment]
Meili team will not have the time to work on it, sorry. We are a really small team so we have to try to prioritize our tasks. However any contributions are welcome and we will be ready to review them 😊

**Comment by botbotbotbotboot** [comment]
@curquiza Would you be open to bounties?. I tried to do this but didnt reach far. 

https://console.algora.io/bounties/clsd5ih5e0006jy0fja0imiu0

**Comment by ellnix** [comment]
I can probably do this, but it will take some reengineering with the current code base, and we should probably discuss API since there is nothing like it currently in the gem.

**Comment by ellnix** [comment]
The primary challenge is matching index names to models, which we reasonably cannot do and therefore will be passed on as a responsibility to the user. 

Currently I can think of:
1. Lazy-evaluating `search` with an in-between array-like class so we can add method chaining like ActiveRecord Relation. Think `Product.search('thing').and(Book.search('paper'))`. 
    - Difficult to use if the searches are not predetermined
    - Complex to implement, certainly qualifies as a breaking change
2. A separate multi-search method
    1. Model-centric 
    ```ruby 
    MeiliSearch::Rails.multi_search(
      Book => {q: 'paper', **book_options}, # Model with implied index
      Product => {q: 'thing', **product_options}, 
    **other_searches)
    ```

    2. Index-centric 
    ```ruby
    MeiliSearch::Rails.multi_search(
      'book_production' => {q: 'paper', class_name: 'Book', **book_options}, # Index with a model
      'stuff_production' => {q: 'thing', class_name: 'Product', **product_options},
      'blurbs' => { q: 'happy' }, # Index not backed by a model, results will be simple hashes
      **other_searches)
    ```
    
    3. Polymorphic (both model-centric and index-centric)
    
    ```ruby
    MeiliSearch::Rails.multi_search(
      'book_production' => {q: 'paper', class_name: 'Book', **book_options}, # Index with a model
      Product => {q: 'thing', **product_options}, # Model with implied index
      'blurbs' => { q: 'happy' }, # Index not backed by a model, results will be simple hashes
      **other_searches)
    ```
    
Personally I prefer `2. iii.` the polymorphic dedicated method, despite how messy it looks in the example above, it would allow for the most options and flexibility. I am open to other suggestions and will also add any others I can think of.

**Comment by curquiza** [comment]
> @curquiza Would you be open to bounties?.

No, we don't have a bounty for opensource contributions

**Comment by curquiza** [comment]
Thank you @ellnix 
let know now if you need review on anything. I talked with Bruno and we will try to be reactive on this

**Comment by zcesur** [comment]
> Created bounty on algora but i think you will have to add app and accept or something :
> https://console.algora.io/bounties/clsd5ih5e0006jy0fja0imiu0

hey algora cofounder here :wave: meilisearch team can accept the bounty here if they'd like! https://algora.io/invitation/meilisearch

**Comment by botbotbotbotboot** [comment]
Just checking to make sure,

If I have two models, Question and Reply, then to search both of them at once, do I need this feature? Is there any other way of doing it that I don't know about?

I'm curious because it seems like a common use case for a search product.

**Comment by ellnix** [comment]
> If I have two models, Question and Reply, then to search both of them at once, do I need this feature? Is there any other way of doing it that I don't know about?

Well not necessarily:
- You could include the reply in the questions index as a custom attribute (see [the README](https://github.com/meilisearch/meilisearch-rails/?tab=readme-ov-file#relations))
- You could make Questions and Replies share an index and search that index (see [the README](https://github.com/meilisearch/meilisearch-rails/?tab=readme-ov-file#share-a-single-index))
- You could use `multi_search` directly on `MeiliSearch::Rails.client` (not recommended)

**Comment by botbotbotbotboot** [comment]
Making "Questions and Replies share an index and search that index" could works for me. 

Let me try, Thanks.

**Comment by botbotbotbotboot** [comment]
Thank you for merging this, can you share some pointers on using it?

`MeiliSearch::Rails.multi_search` is giving undefined method.

**Comment by ellnix** [comment]
> Thank you for merging this, can you share some pointers on using it?
> 
> `MeiliSearch::Rails.multi_search` is giving undefined method.

It has just been implemented, it will be made available in the next release.
I will also make a PR to add usage to the README.
