### ISSUE TITLE
Timing out while trying to index data on Meilisearch Cloud on windows WSL2 Ubuntu

### ISSUE THREAD

**Issue by nparoski** [meilisearch/meilisearch-rails#260]
**Description**
When trying to index data on Meilisearch Cloud I always timeout after ceratin amount of data is indexed, first time I got this working is when I set timeout to 1000ms but now it's not working even after 60000ms.

~~When indexing outside of WSL 2 env it seems to be okay but it's not an option.~~
Just set it up and tried outside of WSL 2, same thing doesn't work. Also I should add that this is inside of docker container.

I am from Europe and even servers on Frankfurt / London fail.
My upload is 20-30 MB/s and download about 200.
Processor: AMD 5 5600x 
Ram: 16 GB

**Screenshots or Logs**
![image](https://github.com/meilisearch/meilisearch-rails/assets/35550355/95670739-2c98-460e-a5fe-4bd930d0aff7)

**Environment (please complete the following information):**
- WSL 2 Ubuntu
- Meilisearch Cloud
- meilisearch-rails version: [e.g v0.9.1]
- Rails version: [e.g. 7.04]

**Comment by nparoski** [comment]
Interesting thing i noticed just before it timed out
![image](https://github.com/meilisearch/meilisearch-rails/assets/35550355/d08c4a59-e43d-41d1-b1d1-3e844654b81b)

After stopping download
![image](https://github.com/meilisearch/meilisearch-rails/assets/35550355/59f3918d-e612-42b7-9cfe-89ff5fe3b504)

**Comment by nparoski** [comment]
Also just now it failed while it was mesuring 15-19 Mbps

![image](https://github.com/meilisearch/meilisearch-rails/assets/35550355/2ba7d3a9-a2dd-4e64-b225-c1a81699f1fe)

**Comment by oluademola** [comment]
Hello @nparoski. Sorry for the inconvenience. From the error message, it looks to me the cloud instance is not in a running state. Can you double-check that, please?

**Comment by nparoski** [comment]
@oluademola Double checked, it's in running state also it indexes some random amount of data e.g 61, 12, 32 before failing.
There's total 101 that needs to be indexed.
![image](https://github.com/meilisearch/meilisearch-rails/assets/35550355/df2a2ec6-489e-48e5-9843-122c404232ee)

**Comment by nparoski** [comment]
Hey @oluademola I'm thinking it's my router possibly? I was able to index everything from another laptop on different network without issues (same setup WSL 2) just failed again on my PC which uses ethernet cable. Switched to wifi (hotspot from my phone network) and it worked first time.

**Comment by oluademola** [comment]
Hello @nparoski. It's possible that the timeout was due to a network problem. I also tried to replicate the issue, but couldn't. I believe this might not be an actual bug, but please feel free to inform us if you come across any other problems. Thanks!

**Comment by brunoocasali** [comment]
I'm closing this due to a lack of news. Please reopen if needed!
