### ISSUE TITLE
will_paginate issue

### ISSUE THREAD

**Issue by jason-hobbs** [meilisearch/meilisearch-rails#261]
I am using the latest Meilisearch gem with the latest Meilisearch runtime on Rails 7.0.5
I am integreating Meilisearch and am trying to use will_paginate.  I have my backend set to will_paginate in the config and have wiil_paginate @searchresults in the view.  This works well but any page I go to only displays the first page.  Do I have to set offset or something similar?

**Comment by brunoocasali** [comment]
Hi @jason-hobbs!

We have some integration test cases in this repo that are using will_paginate, and they seem to be working fine.

Do you have something like this in your code?

`hits = Movie.search 'avenger', hits_per_page: 5, page: 2`

**Comment by jason-hobbs** [comment]
Well turns out I am an idiot.  I forgot the page param.  Sorry about the ticket.

**Comment by brunoocasali** [comment]
Don't worry I'm here to help, I'm glad it works 🎉
