### ISSUE TITLE
Race condition in async removal after destroy

### ISSUE THREAD

**Issue by georgeclaghorn** [meilisearch/meilisearch-rails#266]
With `enqueue: true`, an `after_destroy` callback is added which enqueues a `MeiliSearch::Rails::MSJob` intended to remove the destroyed record from the Meilisearch index:

https://github.com/meilisearch/meilisearch-rails/blob/b9b5efb219c8926551da1caf7566e8d1b2071c9f/lib/meilisearch-rails.rb#L443-L444

https://github.com/meilisearch/meilisearch-rails/blob/b9b5efb219c8926551da1caf7566e8d1b2071c9f/lib/meilisearch-rails.rb#L881-L889

https://github.com/meilisearch/meilisearch-rails/blob/b9b5efb219c8926551da1caf7566e8d1b2071c9f/lib/meilisearch-rails.rb#L367-L384

Line 372 above passes the destroyed record as an argument to the job. Active Job [transparently serializes](https://guides.rubyonrails.org/active_job_basics.html#globalid) the record to a [Global ID](https://github.com/rails/globalid) on enqueue and looks up the record from the Global ID when the job is performed.

The enqueued background job may be performed after the transaction wrapping the record’s destruction has committed. In this case, Active Job won’t be able to find the record in the DB from its Global ID, and the `MSJob` will fail with an `ActiveJob::DeserializationError`.

From a quick look, it seems that the plugin’s tests don’t catch this because they only assert that a job is enqueued with the correct arguments. They might have caught it if they exercised the end-to-end destroy→enqueue→perform flow using `ActiveJob::TestHelper`’s [`perform_enqueued_jobs`](https://github.com/rails/rails/blob/fe8575ed55ab3617339c2623a2993e510381b724/activejob/lib/active_job/test_helper.rb#L598-L627) or similar.

Suggested fix:
1. Replace the `after_destroy` with an `after_destroy_commit` callback.
2. Update the job to take a model and record ID as arguments. (Alternatively, add a new job to avoid breaking changes to the existing background job’s signature.)
3. Attempt to look up the record. If it exists, index it. If it doesn't, delete it from the index.
   ```ruby
   def perform(model, id)
     if record = model.unscoped.find_by(id: id)
       record.ms_index!
     else
       model.ms_remove_document_from_index_by_id!(id)
     end
   end
   ```

Further reading: [`elasticsearch-model`’s documentation](https://github.com/elastic/elasticsearch-rails/tree/main/elasticsearch-model#asynchronous-callbacks) includes an example Sidekiq job implementing an alternative approach (taking an operation name argument rather than using the record’s existence to decide what to do).

History:
* algolia/algoliasearch-rails#75
* algolia/algoliasearch-rails#359
* algolia/algoliasearch-rails#369
* algolia/algoliasearch-rails#422

**Comment by brunoocasali** [comment]
Hi @georgeclaghorn, thanks for your full debugging and plan to fix the bug!

I want to do it, but unfortunately, I can't now. The integrations team is changing how we work, so it could take a while until we have enough time to progress in issues like this.

Although, I would love to review a PR if you're willing to contribute! ❤️
