### ISSUE TITLE
Return task object after ms_index!

### ISSUE THREAD

**Issue by mech** [meilisearch/meilisearch-rails#271]
**Description**

I wish that indexing can return task object so I can get back the `taskUid` and perform lookup to see if indexing succeeded or not

**Basic example**

```ruby
c = Company.first
task = c.ms_index!

task_id = task["taskUid"]

# Later I can check
MeiliSearch::Rails.client.task(task_id)
```

Currently if indexing failed for whatever reason, it could be misconfiguration, it is hard to tell.

**Comment by brunoocasali** [comment]
Good idea @mech 👍
