### ISSUE TITLE
Add support for distinct attribute

### ISSUE THREAD

**Issue by jeremylynch** [meilisearch/meilisearch-rails#272]
Would be great if we could support the `distinctAttribute` 

https://www.meilisearch.com/docs/learn/configuration/distinct

**Comment by brunoocasali** [comment]
Hi @jeremylynch!

Have you tried this?

```rb
class Book < ApplicationRecord
  include MeiliSearch::Rails

  meilisearch do
    distinct_attribute [:title]
  end
end
```

**Comment by brunoocasali** [comment]
I believe this is not an error since we have this config declared here: `lib/meilisearch-rails.rb:55`
