### ISSUE TITLE
Options `primary_key` vs `id`

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-rails#28]
From my POV these two options seem to do the same: inform MeiliSearch about the unique identifier.
If they indeed to the same, we should remove one to keep only the other one.

**Comment by CaroFG** [comment]
In the integration_spec file `id:` is used on class Cat and class Dog (lines 220, 226, 233 and 239). Everywhere else we use primary_key. One or the other should be changed if we decide to keep just one identifier.

**Comment by curquiza** [comment]
Checked with @CaroFG.
Both options are available (`:id` and `:primary_key`). Only `primary_key` is documented. If both options are set, `primary_key` is prioratized.
