### ISSUE TITLE
Initial index creation and indexing

### ISSUE THREAD

**Issue by crespire** [meilisearch/meilisearch-rails#284]
Hey folks, new to using Meilisearch and really enjoying it so far. We are about to switch from `pg_search` to `meilisearch-rails` and I had a question about first-time setup.

I understand that Meili will auto-index via AR callbacks on any new records, but if we have existing records, it doesn't seem that Meiliesearch will index anything until I manually call `reindex!`.

Perhaps I have configured incorrectly?

I tried to do an `after_initialization` block but it is failing because the index does not yet exist? I'm not sure what the issue is:

```rb
# End of config/meilisearch.rb

Rails.configuration.after_initialize do
  unless Rails.env.test?
    Rails.logger.info 'Checking for Meilisearch index...'

    # Always attempt to create the index. Meilisearch requires indexes to be unique
    # If index already exists, this will fail silently
    client = MeiliSearch::Client.new(ENV['MEILISEARCH_HOST'], ENV['MEILISEARCH_MASTER_KEY'])
    client.create_index('Resource', primary_key: 'id')

    if Resource.index.number_of_documents.zero?
      Rails.logger.info 'Melisearch index empty, starting reindex.'
      ReindexTextSearchJob.new.perform
    else
      Rails.logger.info 'Meilisearch index populated, skipping reindex.'
    end
  end
end
```

I keep getting a fatal error when my CI runs `assets:precompile`:
```bash
-----> /home/deploy/.asdf/bin/asdf exec bundle exec rake assets:precompile
rake aborted!
MeiliSearch::ApiError: 404 Not Found - Index `PressRelease` not found.. See https://docs.meilisearch.com/errors#index_not_found.
```

Is there a way for me to automate a `Create and index resources if an index does not exist` task after initial deployment? I know Meilisearch Rails will pick up if a record is created via AR callbacks.

**Comment by brunoocasali** [comment]
Hi @crespire!

What is the configuration of your model? Because you're creating an index called `Resource` and the error shows a different name, `PressRelease`.

You can tweak the name of the index if you want (just take a look at the readme) :)

**Comment by crespire** [comment]
Hmm, I will investigate. We've pursued the solution of running an after-deploy rake task to reindex as part of our deployment process, so I'll close the issue now.

Thanks @brunoocasali, appreciate your time and assistance!
