### ISSUE TITLE
Check if attributes have changed before index

### ISSUE THREAD

**Issue by jeremylynch** [meilisearch/meilisearch-rails#288]
Note that the Algolia equivalent of this gem indexes documents only if attribute(s) have changed. This is [described here](https://www.algolia.com/doc/framework-integration/rails/indexing/indexing/?client=ruby#indexing-only-if-attributes-have-changed). Does meilisearch-rails have the same feature?

**Comment by ellnix** [comment]
Yes, meilisearch-rails has the same feature. However, it only uses the newer `will_save_change_to_#{attr}` syntax. It is referenced in passing in the README of this repo: https://github.com/meilisearch/meilisearch-rails/#custom-attribute-definition.

See the implementation:
https://github.com/meilisearch/meilisearch-rails/blob/e7a12569f18ee40684c3c643a3cf573f3465c62e/lib/meilisearch-rails.rb#L853C1-L853C1
