### ISSUE TITLE
All CI tests with Rails 7 fail

### ISSUE THREAD

**Issue by ellnix** [meilisearch/meilisearch-rails#306]
**Description**
All GitHub actions jobs with Rails 7 fail. This means that no PRs can be merged currently.

After almost 2 hours of trying to find out why:
- Although the `tests.yml` file specifies `RAILS_VERSION: 7.0` which should prevent bundler from going to `7.1` (due to the pessimistic version constraint `~>`) the workflow is now run with Rails [`7.1.0`](https://github.com/meilisearch/meilisearch-rails/actions/runs/6341168191/job/18040971613?pr=299#step:3:229) while in the past it was run with Rails [`7.0.x`](https://github.com/meilisearch/meilisearch-rails/actions/runs/6341168191/job/18040971613?pr=299#step:3:103)
  - I do not know why this happens, maybe Github actions casts 7.0 to an int somehow?
- The `sqlite3` package on `Ubuntu 20.04` seems to have compatibility with [sqlite changes in Rails 7.1](https://edgeguides.rubyonrails.org/7_1_release_notes.html#active-record-notable-changes), resulting in all database-backed tests failing
  - Ubuntu freezes package versions and only provides security updates to them in LTS releases
  
  
We should either 
- specify `7.0.8` as the Rails 7 version (not preferred, we just kick the problem down the road)
- change the OS used in github actions to something more modern

P. S.: I am still investigating this, `sqlite3` is just my working theory for the moment, but it could be a different compatibility issue.

Edit 1: It definitely is `sqlite`, I confirmed it by switching to postgres on a vm. `sqlite` has the same errors as github actions while `postgres` passes all tests.
[postgres_rspec_run.log](https://github.com/meilisearch/meilisearch-rails/files/13166531/postgres_rspec_run.log)
[sqlite_rspec_run.log](https://github.com/meilisearch/meilisearch-rails/files/13166532/sqlite_rspec_run.log)

**Comment by brunoocasali** [comment]
I think we can switch to a newer version of the OS @ellnix :)
