### ISSUE TITLE
Semantic Search using Embeddings

### ISSUE THREAD

**Issue by AliOsm** [meilisearch/meilisearch-rails#324]
**Description**
Meilisearch is currently supporting vector search, I think adding support to meilisearch-rails for vector search will add a lot of values to ActiveModel and how to use them for searching. Instead of talking with the API directly.

**Basic example**
I created a very basic gem named [Chromable](https://github.com/AliOsm/chromable) to simplify the integration between Rails and ChromaDB. I think the same idea could be applied in meilisearch-rails.

**Comment by ellnix** [comment]
This looks like a duplicate of #316

**Comment by curquiza** [comment]
Closing in favor of #316 then
