### ISSUE TITLE
single index sharing didnt create new index.

### ISSUE THREAD

**Issue by botbotbotbotboot** [meilisearch/meilisearch-rails#338]
**Description**
Following [docs](https://github.com/meilisearch/meilisearch-rails?tab=readme-ov-file#share-a-single-index) i created a shared index as below:

```
class Answer < ApplicationRecord
  include MeiliSearch::Rails
  
  meilisearch index_uid: "Discussion", primary_key: :ms_id

  belongs_to :question
  meilisearch do
    attribute :title
    attribute :body
  end

  def ms_id
    "answer_#{primary_key}"
  end
end

```
```
class Question < ApplicationRecord
  include MeiliSearch::Rails
  meilisearch index_uid: "Discussion", primary_key: :ms_id
  has_many :answers

  meilisearch do
    attribute :title
    attribute :body
  end

   def ms_id
    "question_#{primary_key}"
  end
end

```
**Expected behavior**
That it will create new index "Discussion"

**Current behavior**
Did not create new Index.

**Screenshots or Logs**
Its ignoring the configuration.

**Environment (please complete the following information):**
- OS: Mac OS 14.1
- Meilisearch server version: 1.5.1
- meilisearch-rails version: 0.11.1
- Rails version: 7.1

**Comment by ellnix** [comment]
Please only call `meilisearch` once in models and append the block to that one call:
```ruby
class Answer < ApplicationRecord
  include MeiliSearch::Rails
  belongs_to :question
  meilisearch index_uid: "Discussion", primary_key: :ms_id do
    attribute :title
    attribute :body
  end

  def ms_id
    "answer_#{primary_key}"
  end
end
```

```ruby
class Question < ApplicationRecord
  include MeiliSearch::Rails
  has_many :answers
  
  meilisearch index_uid: "Discussion", primary_key: :ms_id do
    attribute :title
    attribute :body
  end

   def ms_id
    "question_#{primary_key}"
  end
end
```

I believe the second call to `meilisearch` was overwriting the first. Please let me know if this fixes it :smile:.

**Comment by botbotbotbotboot** [comment]
```
class Question < ApplicationRecord
  include MeiliSearch::Rails
  has_many :answers

  meilisearch index_uid: "Discussion", primary_key: :ms_id do
    attribute :title
    attribute :body
  end

   def ms_id
    "question_#{id}"
  end
end
```

Ok this worked!. Thank you.

Now, i can search by `Question.search()` and it will query both models right?

**Comment by ellnix** [comment]
> Now, i can search by `Question.search()` and it will query both models right?

I have to apologize, I thought you could but it turns out that is not what the gem does. Please use this as a temporary fix (replace `QUERY_HERE` with the search query):
```ruby
Question.index.search(QUERY_HERE)['hits'].map do |result|
  klass, id = result['ms_id'].split('_')
  case klass
  when 'question'
    Question.find(id)
  when 'answer'
    Answer.find(id)
  end
end
```

I have to make some proposals to make the straightforward `Question.search` work.
