### ISSUE TITLE
Polymorphic shared indexes 

### ISSUE THREAD

**Issue by ellnix** [meilisearch/meilisearch-rails#340]
**Description**
The current implementation of shared indexes is deeply flawed, it:
- It does not by default exclude the custom primary key from being searchable (meaning searching for "dog" when `ms_id` is `"dog_#{id}"` will return every dog)
<details><summary>Reproduce</summary> <p>

```ruby

require 'bundler/inline'

gemfile do
  gem "rails", "~> 7.1.3"
  gem "sqlite3", "~> 1.4"
  gem "meilisearch-rails", "~> 0.11.1"
end

MeiliSearch::Rails.configuration = {
  meilisearch_url: ENV.fetch('MEILISEARCH_HOST', 'http://localhost:7700'),
  meilisearch_api_key: ENV.fetch('MEILISEARCH_API_KEY', 'masterKey')
}

FileUtils.rm('data.sqlite3') if File.exist?('data.sqlite3')

require 'active_record'

ActiveRecord::Base.establish_connection(
  'adapter' => defined?(JRUBY_VERSION) ? 'jdbcsqlite3' : 'sqlite3',
  'database' => 'data.sqlite3',
  'pool' => 5,
  'timeout' => 5000
)

ActiveRecord::Schema.define do
  create_table(:dogs) { |t| t.string :name }
end

class Dog < ActiveRecord::Base
  include MeiliSearch::Rails

  meilisearch index_uid: 'animals', primary_key: :ms_id

  def ms_id
    "dog_#{id}"
  end
end

Dog.create name: 'toby' 
Dog.create name: 'spikey'
Dog.create name: 'doggy'

sleep 0.5

p Dog.search 'dog' # Will return all dogs
```
</p>
</details> 

- May fetch from the database IDs that belong to another model unnecessarily (not a big problem but would be nice if it didn't)
- Does not provide an option to search the index and return a _polymorphic_ collection with results from multiple models

These problems stem from the fact that the custom primary key cannot be used for lookup or to know the model name of the document in meilisearch.

**Basic example**

I would suggest instead of allowing the user to specify a primary key for a shared index, we instead allow them to pass a `shared_index: 'index_name'` option, which would add two non searchable fields in the meilisearch instance: `_ms_model` and `_ms_pk`. With this set up:
- we could get the search results from the shared index and fetch instances from multiple models for situations like [this](https://github.com/meilisearch/meilisearch-rails/issues/338#issuecomment-1968742600)
- shared indexes would be simpler to set up, involving no custom methods and the gem would avoid conflicts (convention over configuration)

Example:

```ruby
class Tiger < ActiveRecord::Base
  include MeiliSearch::Rails

  meilisearch shared_index: 'animals'
end

class Cat < ActiveRecord::Base
  include MeiliSearch::Rails

  meilisearch shared_index: 'animals'
end

class Puma
  include MeiliSearch::Rails

  meilisearch do
    add_shared_index 'animals'
  end
end

Tiger.create name: 'toby'
Cat.create name: 'tobias'
Puma.create name: 'tobs'

p Cat.search 'tob'
# [#<Tiger id: 1, name: "toby">, #<Cat id: 1, name: "tobias">, #<Puma id: 1, name: "tobs">]
```

**Comment by brunoocasali** [comment]
`p Cat.search 'tob'`

Even knowing the user defined the shared indexes everywhere, seems weird to me that they could have a polymorphic list of models while searching from one of the implementations in this case the `Cat` one.

I like the approach of #341 where we have a clear entity that is responsible for doing that.

**Comment by ellnix** [comment]
Closing in favor of #341
