### ISSUE TITLE
hitsPerPage param does not work

### ISSUE THREAD

**Issue by molfar** [meilisearch/meilisearch-rails#41]
Following the docs I try to limit number of results

`products = Product.search params[:query], hitsPerPage: 9`

But I got and error

`MeiliSearch::ApiError (400 Bad Request - Invalid JSON: unknown field hitsPerPage, expected one of q, offset, limit, attributesToRetrieve, attributesToCrop cropLength, attributesToHighlight, filters, matches, facetFilters, facetsDistribution at line 1 column 29. See https://docs.meilisearch.com/errors#bad_request.)`

Changing param name to "limit" (as exception message explains) - solves the problem

`products = Product.search params[:query], limit: 9`

Moreover, with Rails style guide, camelcase names for params is not acceptable, undersored names should be used.

**Comment by CaroFG** [comment]
Hi! This error should not appear when using the [`:pagination_backend` option](https://github.com/meilisearch/meilisearch-rails#backend-pagination-) on your configuration file, as the `hitsPerPage` option it's supposed to be used when using pagination. Have you set the `:pagination_backen` option and are still getting this error? Anyway, thanks for spotting this, we should update our README to make it clear that this option only works when pagination is being used.

**Comment by CaroFG** [comment]
I just opened this issue to improve pagination documentation: #42

**Comment by molfar** [comment]
I dont use any pagination, just need to limit results. And yeh, the documentation is not clear enough about it. By the way, there is another excellent pagination gem called [Pagy](https://github.com/ddnexus/pagy) which gradually displaces both both will_paginate and kaminary. As for me, Pagy is my favourite one.

**Comment by curquiza** [comment]
see #43

**Comment by CaroFG** [comment]
Opened new issue for case convention :) #44

**Comment by CaroFG** [comment]
Closing this one as #42 should solve the confusion
