### ISSUE TITLE
Make this gem work with Pagy

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-rails#43]
https://github.com/ddnexus/pagy/

**Comment by bb** [comment]
https://gitter.im/ruby-pagy/Lobby?at=60c339f5747a772d99ea20ed

**Comment by curquiza** [comment]
Thanks for this information @bb!!

**Comment by molfar** [comment]
I've started working on integration with Pagy https://github.com/ddnexus/pagy/pull/313

**Comment by molfar** [comment]
Just finished working on integration with Pagy gem https://github.com/ddnexus/pagy/pull/316 New feature is available to under dev branch.

**Comment by bb** [comment]
@ddnexus released it in pagy version 4.9 https://github.com/ddnexus/pagy/blob/master/CHANGELOG.md 

Thanks @molfar and @ddnexus! 😃

**Comment by curquiza** [comment]
Awesome! All the Meili team thanks you @molfar and @ddnexus!! 😄
Have you a twitter account @molfar and @ddnexus? We would like to highlight your work with the MeiliSearch twitter account, if you agree with this of course!

**Comment by curquiza** [comment]
(I close this issue, but feel free to answer my question here)

**Comment by ddnexus** [comment]
@curquiza I have no twitter account, however you are welcome to post about it.

Also... your README should add pagy to the note about supported pagination now.
