### ISSUE TITLE
Error when enabling paging with Ruby3 / kaminari

### ISSUE THREAD

**Issue by nykma** [meilisearch/meilisearch-rails#60]
**Description**
After enabling pagination using `{pagination_backend: :kaminari}` , any search will throw an error.

**Expected behavior**
`MyModel.search()` should work

**Current behavior**

```
ArgumentError: wrong number of arguments (given 2, expected 0..1)
from /home/nykma/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/kaminari-core-1.2.1/lib/kaminari/models/array_extension.rb:18:in `initialize'
```

**Environment:**
- OS: Linux
- MeiliSearch version: 0.20.0
- meilisearch-rails version: 0.2.1
- Rails version: 6.1.4

**Comment by nykma** [comment]
Oh, I kinda got it.
In Ruby3, Hash worked as named parameter should be parsed like `**options`
Maybe some changes should be made in 
https://github.com/meilisearch/meilisearch-rails/blob/main/lib/meilisearch/pagination/kaminari.rb#L12
 for a compatability of ruby3

**Comment by curquiza** [comment]
Thanks for the bug report and the investigation 🙂
