### ISSUE TITLE
Ability to change the index uid during run time?

### ISSUE THREAD

**Issue by krisquigley** [meilisearch/meilisearch-rails#65]
Is there a way of changing the `index_uid` during runtime?

I'm creating a SaaS app and want to have one index per user:

```ruby
  meilisearch index_uid: "Story_#{ActsAsTenant.current_tenant&.name}_#{Rails.env}",
              synchronous: Rails.env.test?,
              enqueue: !Rails.env.test?,
              unless: :completed_and_one_off? || :discarded? do
    attribute :goal, :reason, :repeatable, :id

    attribute :values do
      values.map(&:name)
    end

    searchable_attributes %i[goal reason values]
  end
```

This works fine in test and development environments, however in production the `index_uid` is never re-evaluated and breaks the implementation.  Is there a way around this, or should I be taking a different approach?

**Comment by CaroFG** [comment]
Hi! I may have misunderstood your question, if so please excuse me. As stated in the [dedicated section of the documentation](https://docs.meilisearch.com/learn/core_concepts/indexes.html#index-uid), the index uid is set at index creation time. Once a uid has been defined for an index, you cannot create another index with the same uid and the identifier cannot be changed anymore.

**Comment by krisquigley** [comment]
Hi @CaroFG, thanks for getting back to me. 

Does that mean that I cannot create a unique index for each user of my app on the same model?

If so, I would probably need to index the `account_id` and then add a filter to `Story.search` to filter by the `account_id` for that user.  If I take this approach, is there a way of providing a default filter for the model so that it always filters by the `account_id` without having to define it each time?

I'm trying to ensure that no data is leaked between users, as they will be sharing an index in this case.

Thanks!

**Comment by krisquigley** [comment]
Thanks for the heads up and explanation @CaroFG!  I'll keep on eye on the discussions.

**Comment by archonic** [comment]
FYI for anyone else, tenant tokens were introduced in v0.26.0 https://github.com/meilisearch/product/issues/51#issuecomment-948289010
