### ISSUE TITLE
Add rubocop

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-rails#7]
Add rubocop (linter):
- in the Gemfile (dev group)
- in the CI
- how to launch it in the CONTRIBUTING

**Comment by brunoocasali** [comment]
@curquiza I've started this locally and I had some concerns about this:

- Do Meilisearch team have a set of rubocop constraints (overrides) to be used already or I'm free to suggest mine?
- After the first execution without any overrides I got: `73 files inspected, 823 offenses detected, 684 offenses auto-correctable` probably we will not refactor the entire gem in one big bang PR right? I could submit multiple pull requests with different contexts like (one for specs and so on...)

**Comment by curquiza** [comment]
Hello @brunoocasali! Thank for starting this huge work!

> Do Meilisearch team have a set of rubocop constraints (overrides) to be used already or I'm free to suggest mine?

Nope, not at the moment

> After the first execution without any overrides I got: 73 files inspected, 823 offenses detected, 684 offenses auto-correctable probably we will not refactor the entire gem in one big bang PR right? I could submit multiple pull requests with different contexts like (one for specs and so on...)

Yes, do multiple PRs is a good way to handle this issue 🙂

**Comment by brunoocasali** [comment]
@curquiza I'll try to generate the PR's separately in two ways:

- by directory 
- by kind of change

Because if I merge both of the operations at the same PR, probably maintainers will have a bad time finding something relevant, a meaningful change or a problematic one for example.
